services:
  - type: web
    name: oliverflix-scraper-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.puppeteer_cache
      - key: NODE_ENV
        value: production
      - key: TARGET_BASE_URL
        value: https://net22.cc
