services:
  - type: web
    name: oliverflix-scraper-api
    env: node
    # Ensure puppeteer cache is saved within the retained project folder
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.puppeteer_cache
      - key: NODE_ENV
        value: production
      - key: TARGET_BASE_URL
        value: https://net22.cc
      - key: CHROME_ARGS
        value: "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-gpu"
